package com.bahn.casestudy.help;

import java.io.IOException;

/**
 * Gets thrown if the CSV file cannot be read.
 */
public class CannotReadCsvException extends IOException {
	/** Generated by Eclipse. */
	private static final long serialVersionUID = 4696787236179386309L;

	/**
	 * The constructor.
	 * @param message The information about the exception the should be carried.
	 */
	public CannotReadCsvException(String message) {
		super(message);
	}
}
