package com.bahn.casestudy.help;

/**
 * Thrown if an operation site is not in the CSV.
 */
public class OperationSiteNotFoundException extends Exception {
	/** Generated by Eclipse. */
	private static final long serialVersionUID = -9093874140087115289L;
	
	/**
	 * The constructor.
	 * @param message The message carried by the exception.
	 */
	public OperationSiteNotFoundException(String message) {
		super(message);
	}
}
